"""
VTU 2022 & 2025 Scheme Subject/Credit Catalog

Real subject codes, titles, semesters, and credits transcribed directly from
official vtu.ac.in scheme-of-teaching-and-examinations PDFs. A handful of rows
note "[pattern-inferred...]" in the title where the exact code was not
independently verified for that specific branch (reconstructed from a
confirmed sibling branch in the same VTU stream) -- everything else is a
direct transcription.
"""

CATALOG_2022 = [
    ("BMATS101", "Mathematics-I for CSE Stream", 4, 1, "CS"),
    ("BPHYS102", "Applied Physics for CSE Stream", 4, 1, "CS"),
    ("BCHES102", "Applied Chemistry for CSE Stream", 4, 1, "CS"),
    ("BPOPS103", "Principles of Programming Using C", 3, 1, "CS"),
    ("BCEDK103", "Computer-Aided Engineering Drawing", 3, 1, "CS"),
    ("BESCK104x", "Engineering Science Course-I", 3, 1, "CS"),
    ("BETCK105x", "Emerging Technology Course-I / Programming Language Course-I", 3, 1, "CS"),
    ("BENGK106", "Communicative English / Professional Writing Skills in English", 1, 1, "CS"),
    ("BICOK107", "Indian Constitution / Samskrutika Kannada / Balake Kannada", 1, 1, "CS"),
    ("BIDTK158", "Innovation and Design Thinking / Scientific Foundations of Health", 1, 1, "CS"),
    ("BMATS201", "Mathematics-II for CSE Stream", 4, 2, "CS"),
    ("BCHES202", "Applied Chemistry for CSE Stream", 4, 2, "CS"),
    ("BPHYS202", "Applied Physics for CSE Stream", 4, 2, "CS"),
    ("BCEDK203", "Computer-Aided Engineering Drawing", 3, 2, "CS"),
    ("BPOPS203", "Principles of Programming Using C", 3, 2, "CS"),
    ("BESCK204x", "Engineering Science Course-II", 3, 2, "CS"),
    ("BETCK205x", "Programming Language Course-II / Emerging Technology Course-II", 3, 2, "CS"),
    ("BPWSK206", "Professional Writing Skills in English / Communicative English", 1, 2, "CS"),
    ("BICOK207", "Indian Constitution / Samskrutika Kannada / Balake Kannada", 1, 2, "CS"),
    ("BIDTK258", "Innovation and Design Thinking / Scientific Foundations of Health", 1, 2, "CS"),
    ("BCS301", "Mathematics for Computer Science", 4, 3, "CS"),
    ("BCS302", "Digital Design & Computer Organization", 4, 3, "CS"),
    ("BCS303", "Operating Systems", 4, 3, "CS"),
    ("BCS304", "Data Structures and Applications", 3, 3, "CS"),
    ("BCSL305", "Data Structures Lab", 1, 3, "CS"),
    ("BCS306x", "ESC/ETC/PLC (e.g. Object Oriented Programming with Java/C++)", 3, 3, "CS"),
    ("BSCK307", "Social Connect and Responsibility", 1, 3, "CS"),
    ("BCS358x", "Ability Enhancement Course/Skill Enhancement Course-III", 1, 3, "CS"),
    ("BCS401", "Analysis & Design of Algorithms", 3, 4, "CS"),
    ("BCS402", "Microcontrollers", 4, 4, "CS"),
    ("BCS403", "Database Management Systems", 4, 4, "CS"),
    ("BCSL404", "Analysis & Design of Algorithms Lab", 1, 4, "CS"),
    ("BCS405x", "ESC/ETC/PLC (Discrete Math/Graph Theory/Optimization/Linear Algebra)", 3, 4, "CS"),
    ("BCS456x", "Ability Enhancement Course/Skill Enhancement Course-IV", 1, 4, "CS"),
    ("BBOC407", "Biology for Computer Engineers", 2, 4, "CS"),
    ("BUHK408", "Universal Human Values Course", 1, 4, "CS"),
    ("BCS501", "Software Engineering & Project Management", 3, 5, "CS"),
    ("BCS502", "Computer Networks", 4, 5, "CS"),
    ("BCS503", "Theory of Computation", 4, 5, "CS"),
    ("BCSL504", "Web Technology Lab", 1, 5, "CS"),
    ("BCS515x", "Professional Elective Course (Computer Graphics/AI/Unix/Distributed Systems)", 3, 5, "CS"),
    ("BCS586", "Mini Project", 2, 5, "CS"),
    ("BRMK557", "Research Methodology and IPR", 3, 5, "CS"),
    ("BCS508", "Environmental Studies and E-waste Management", 2, 5, "CS"),
    ("BCS601", "Cloud Computing (Open Stack/Google)", 4, 6, "CS"),
    ("BCS602", "Machine Learning", 4, 6, "CS"),
    ("BXX613x", "Professional Elective Course (Blockchain/Compiler Design/Computer Vision/Adv Java)", 3, 6, "CS"),
    ("BXX654x", "Open Elective Course (Data Structures/OS/Mobile App Dev/Intro to AI)", 3, 6, "CS"),
    ("BCS685", "Project Phase I", 2, 6, "CS"),
    ("BCSL606", "Machine Learning Lab", 1, 6, "CS"),
    ("BXX657x", "Ability Enhancement Course/Skill Development Course-V (Tosca/React/GenAI/DevOps)", 1, 6, "CS"),
    ("BCS701", "Internet of Things", 4, 7, "CS"),
    ("BCS702", "Parallel Computing", 4, 7, "CS"),
    ("BCS703", "Cryptography & Network Security", 4, 7, "CS"),
    ("BCS714x", "Professional Elective Course (Deep Learning/NLP/Social Network Analysis/Big Data)", 3, 7, "CS"),
    ("BCS755x", "Open Elective Course (Intro to DBMS/Algorithms/Software Engg)", 3, 7, "CS"),
    ("BCS786", "Major Project Phase-II", 6, 7, "CS"),
    ("BCS801x", "Professional Elective (Online, NPTEL)", 3, 8, "CS"),
    ("BCS802x", "Open Elective (Online, NPTEL)", 3, 8, "CS"),
    ("BCS803", "Internship (Industry/Research)", 10, 8, "CS"),
    ("BMATS101", "Mathematics-I for CSE Stream", 4, 1, "AI"),
    ("BPHYS102", "Applied Physics for CSE Stream", 4, 1, "AI"),
    ("BPOPS103", "Principles of Programming Using C", 3, 1, "AI"),
    ("BESCK104x", "Engineering Science Course-I", 3, 1, "AI"),
    ("BETCK105x", "Emerging Technology Course-I / Programming Language Course-I", 3, 1, "AI"),
    ("BENGK106", "Communicative English / Professional Writing Skills in English", 1, 1, "AI"),
    ("BKSKK107", "Samskrutika Kannada / Balake Kannada / Indian Constitution", 1, 1, "AI"),
    ("BIDTK158", "Innovation and Design Thinking / Scientific Foundations of Health", 1, 1, "AI"),
    ("BMATS201", "Mathematics-II for CSE Stream", 4, 2, "AI"),
    ("BCHES202", "Applied Chemistry for CSE Stream", 4, 2, "AI"),
    ("BCEDK203", "Computer-Aided Engineering Drawing", 3, 2, "AI"),
    ("BESCK204x", "Engineering Science Course-II", 3, 2, "AI"),
    ("BETCK205x", "Programming Language Course-II / Emerging Technology Course-II", 3, 2, "AI"),
    ("BENGK206", "Communicative English / Professional Writing Skills in English", 1, 2, "AI"),
    ("BICOK207", "Indian Constitution / Samskrutika Kannada / Balake Kannada", 1, 2, "AI"),
    ("BSFHK258", "Scientific Foundations of Health / Innovation and Design Thinking", 1, 2, "AI"),
    ("BCS301", "Mathematics for Computer Science", 4, 3, "AI"),
    ("BCS302", "Digital Design & Computer Organization", 4, 3, "AI"),
    ("BCS303", "Operating Systems", 4, 3, "AI"),
    ("BCS304", "Data Structures and Applications", 3, 3, "AI"),
    ("BCSL305", "Data Structures Lab", 1, 3, "AI"),
    ("BXX306x", "ESC/ETC/PLC Course-III", 3, 3, "AI"),
    ("BSCK307", "Social Connect and Responsibility", 1, 3, "AI"),
    ("BXX358x", "Ability Enhancement Course/Skill Enhancement Course-III", 1, 3, "AI"),
    ("BCS401", "Analysis & Design of Algorithms", 3, 4, "AI"),
    ("BAD402", "Artificial Intelligence", 4, 4, "AI"),
    ("BCS403", "Database Management Systems", 4, 4, "AI"),
    ("BCSL404", "Analysis & Design of Algorithms Lab", 1, 4, "AI"),
    ("BXX405x", "ESC/ETC/PLC Course-IV", 3, 4, "AI"),
    ("BDS456x", "Ability Enhancement Course/Skill Enhancement Course-IV", 1, 4, "AI"),
    ("BBOK407", "Biology For Engineers", 2, 4, "AI"),
    ("BUHK408", "Universal Human Values Course", 1, 4, "AI"),
    ("BCS501", "Software Engineering & Project Management", 3, 5, "AI"),
    ("BCS502", "Computer Networks", 4, 5, "AI"),
    ("BCS503", "Theory of Computation", 4, 5, "AI"),
    ("BAIL504", "Data Visualization Lab", 1, 5, "AI"),
    ("BXX515x", "Professional Elective Course", 3, 5, "AI"),
    ("BAI586", "Mini Project", 2, 5, "AI"),
    ("BRMK557", "Research Methodology and IPR", 3, 5, "AI"),
    ("BCS508", "Environmental Studies and E-waste Management", 2, 5, "AI"),
    ("BAI601", "Natural Language Processing", 4, 6, "AI"),
    ("BAI602", "Machine Learning-I", 4, 6, "AI"),
    ("BXX613x", "Professional Elective Course", 3, 6, "AI"),
    ("BXX654x", "Open Elective Course", 3, 6, "AI"),
    ("BAI685", "Project Phase I", 2, 6, "AI"),
    ("BAIL606", "Machine Learning Lab", 1, 6, "AI"),
    ("BXX657x", "Ability Enhancement Course/Skill Development Course-V", 1, 6, "AI"),
    ("BAI701", "Deep Learning & Reinforcement Learning", 4, 7, "AI"),
    ("BAI702", "Machine Learning-II", 4, 7, "AI"),
    ("BAD703", "Data Security & Privacy", 4, 7, "AI"),
    ("BAI714x", "Professional Elective Course", 3, 7, "AI"),
    ("BAI755x", "Open Elective Course", 3, 7, "AI"),
    ("BAI786", "Major Project Phase-II", 6, 7, "AI"),
    ("BAI801x", "Professional Elective Course (Online, NPTEL)", 3, 8, "AI"),
    ("BAI802x", "Open Elective Course (Online, NPTEL)", 3, 8, "AI"),
    ("BAI803", "Internship (Industry/Research)", 10, 8, "AI"),
    ("BMATS101", "Mathematics-I for CSE Stream", 4, 1, "DS"),
    ("BPHYS102", "Applied Physics for CSE Stream", 4, 1, "DS"),
    ("BPOPS103", "Principles of Programming Using C", 3, 1, "DS"),
    ("BESCK104x", "Engineering Science Course-I", 3, 1, "DS"),
    ("BETCK105x", "Emerging Technology Course-I / Programming Language Course-I", 3, 1, "DS"),
    ("BENGK106", "Communicative English / Professional Writing Skills in English", 1, 1, "DS"),
    ("BKSKK107", "Samskrutika Kannada / Balake Kannada / Indian Constitution", 1, 1, "DS"),
    ("BIDTK158", "Innovation and Design Thinking / Scientific Foundations of Health", 1, 1, "DS"),
    ("BMATS201", "Mathematics-II for CSE Stream", 4, 2, "DS"),
    ("BCHES202", "Applied Chemistry for CSE Stream", 4, 2, "DS"),
    ("BCEDK203", "Computer-Aided Engineering Drawing", 3, 2, "DS"),
    ("BESCK204x", "Engineering Science Course-II", 3, 2, "DS"),
    ("BETCK205x", "Programming Language Course-II / Emerging Technology Course-II", 3, 2, "DS"),
    ("BENGK206", "Communicative English / Professional Writing Skills in English", 1, 2, "DS"),
    ("BICOK207", "Indian Constitution / Samskrutika Kannada / Balake Kannada", 1, 2, "DS"),
    ("BSFHK258", "Scientific Foundations of Health / Innovation and Design Thinking", 1, 2, "DS"),
    ("BDS301", "Mathematics for Data Science", 4, 3, "DS"),
    ("BCS302", "Digital Design & Computer Organization", 4, 3, "DS"),
    ("BCS303", "Operating Systems", 4, 3, "DS"),
    ("BCS304", "Data Structures and Applications", 3, 3, "DS"),
    ("BCSL305", "Data Structures Lab", 1, 3, "DS"),
    ("BXX306x", "ESC/ETC/PLC", 3, 3, "DS"),
    ("BSCK307", "Social Connect and Responsibility", 1, 3, "DS"),
    ("BXX358x", "Ability Enhancement Course/Skill Enhancement Course-III", 1, 3, "DS"),
    ("BCS401", "Analysis & Design of Algorithms", 3, 4, "DS"),
    ("BDS402", "Computer Networks", 4, 4, "DS"),
    ("BCS403", "Database Management Systems", 4, 4, "DS"),
    ("BCSL404", "Analysis & Design of Algorithms Lab", 1, 4, "DS"),
    ("BXX405x", "ESC/ETC/PLC", 3, 4, "DS"),
    ("BDS456x", "Ability Enhancement Course/Skill Enhancement Course-IV", 1, 4, "DS"),
    ("BBOC407", "Biology for Computer Engineers", 2, 4, "DS"),
    ("BUHK408", "Universal Human Values Course", 1, 4, "DS"),
    ("BCS501", "Software Engineering & Project Management", 3, 5, "DS"),
    ("BDS502", "NoSQL Databases", 4, 5, "DS"),
    ("BCS503", "Theory of Computation", 4, 5, "DS"),
    ("BAIL504", "Data Visualization Lab", 1, 5, "DS"),
    ("BXX515x", "Professional Elective Course", 3, 5, "DS"),
    ("BDS586", "Mini Project", 2, 5, "DS"),
    ("BRMK557", "Research Methodology and IPR", 3, 5, "DS"),
    ("BCS508", "Environmental Studies and E-waste Management", 2, 5, "DS"),
    ("BDS601", "Big Data Analytics", 4, 6, "DS"),
    ("BDS602", "Artificial Intelligence & Machine Learning", 4, 6, "DS"),
    ("BXX613x", "Professional Elective Course", 3, 6, "DS"),
    ("BXX654x", "Open Elective Course", 3, 6, "DS"),
    ("BDS685", "Project Phase I", 2, 6, "DS"),
    ("BCSL606", "Machine Learning Lab", 1, 6, "DS"),
    ("BXX657x", "Ability Enhancement Course/Skill Development Course-V", 1, 6, "DS"),
    ("BDS701", "Parallel Programming", 4, 7, "DS"),
    ("BAD702", "Statistical Machine Learning", 4, 7, "DS"),
    ("BAD703", "Data Security & Privacy", 4, 7, "DS"),
    ("BDS714x", "Professional Elective Course", 3, 7, "DS"),
    ("BDS755x", "Open Elective Course", 3, 7, "DS"),
    ("BDS786", "Major Project Phase-II", 6, 7, "DS"),
    ("BDS801x", "Professional Elective (Online, NPTEL)", 3, 8, "DS"),
    ("BDS802x", "Open Elective (Online, NPTEL)", 3, 8, "DS"),
    ("BDS803", "Internship (Industry/Research)", 10, 8, "DS"),
    ("BMATE101", "Mathematics-I for EEE Streams", 4, 1, "EC"),
    ("BPHYE102", "Applied Physics for EEE Stream", 4, 1, "EC"),
    ("BBEE103", "Basic Electronics for EEE Stream", 3, 1, "EC"),
    ("BESCK104x", "Engineering Science Course-I", 3, 1, "EC"),
    ("BETCK105x", "Emerging Technology Course-I / Programming Language Course-I", 3, 1, "EC"),
    ("BENGK106", "Communicative English / Professional Writing Skills in English", 1, 1, "EC"),
    ("BKSKK107", "Samskrutika Kannada / Balake Kannada / Indian Constitution", 1, 1, "EC"),
    ("BIDTK158", "Innovation and Design Thinking / Scientific Foundations of Health", 1, 1, "EC"),
    ("BMATE201", "Mathematics-II for EES", 4, 2, "EC"),
    ("BCHEE202", "Chemistry for EES", 4, 2, "EC"),
    ("BCEDK203", "Computer-Aided Engineering Drawing", 3, 2, "EC"),
    ("BESCK204x", "Engineering Science Course-II", 3, 2, "EC"),
    ("BPLCK205x", "Programming Language Course-II / Emerging Technology Course-II", 3, 2, "EC"),
    ("BPWKS206", "Professional Writing Skills in English / Communicative English", 1, 2, "EC"),
    ("BICOK207", "Indian Constitution / Samskrutika Kannada / Balake Kannada", 1, 2, "EC"),
    ("BSFHK258", "Scientific Foundations of Health / Innovation and Design Thinking", 1, 2, "EC"),
    ("BMATEC301", "Mathematics-III for EC Engineering", 3, 3, "EC"),
    ("BEC302", "Digital System Design using Verilog", 4, 3, "EC"),
    ("BEC303", "Electronic Principles and Circuits", 4, 3, "EC"),
    ("BEC304", "Network Analysis", 3, 3, "EC"),
    ("BECL305", "Analog and Digital Systems Design Lab", 1, 3, "EC"),
    ("BEC306x", "Engineering Science Course (ESC/ETC/PLC)", 3, 3, "EC"),
    ("BSCK307", "Social Connect and Responsibility", 1, 3, "EC"),
    ("BEC358x", "Ability Enhancement Course/Skill Enhancement Course-III", 1, 3, "EC"),
    ("BEC401", "Electromagnetics Theory", 3, 4, "EC"),
    ("BEC402", "Principles of Communication Systems", 4, 4, "EC"),
    ("BEC403", "Control Systems", 4, 4, "EC"),
    ("BECL404", "Communication Lab", 1, 4, "EC"),
    ("BEC405x", "Engineering Science Course (ESC/ETC/PLC)", 3, 4, "EC"),
    ("BEC456x", "Ability Enhancement Course/Skill Enhancement Course-IV", 1, 4, "EC"),
    ("BBOK407", "Biology For Engineers", 3, 4, "EC"),
    ("BUHK408", "Universal Human Values Course", 1, 4, "EC"),
    ("BEC501", "Technological Innovation and Management Entrepreneurship", 3, 5, "EC"),
    ("BEC502", "Digital Signal Processing", 4, 5, "EC"),
    ("BEC503", "Digital Communication", 4, 5, "EC"),
    ("BECL504", "Digital Communication Lab", 1, 5, "EC"),
    ("BEC515x", "Professional Elective Course", 3, 5, "EC"),
    ("BEC586", "Mini Project", 2, 5, "EC"),
    ("BRMK557", "Research Methodology and IPR", 3, 5, "EC"),
    ("BESK508", "Environmental Studies", 2, 5, "EC"),
    ("BEC601", "Embedded System Design", 4, 6, "EC"),
    ("BEC602", "VLSI Design and Testing", 4, 6, "EC"),
    ("BEC613x", "Professional Elective Course", 3, 6, "EC"),
    ("BEC654x", "Open Elective Course", 3, 6, "EC"),
    ("BEC685", "Major Project Phase I", 2, 6, "EC"),
    ("BECL606", "VLSI Design and Testing Lab", 1, 6, "EC"),
    ("BEC657x", "Ability Enhancement Course/Skill Development Course-V", 1, 6, "EC"),
    ("BEC701", "Microwave Engineering and Antenna Theory", 4, 7, "EC"),
    ("BEC702", "Computer Networks and Protocols", 4, 7, "EC"),
    ("BEC703", "Wireless Communication Systems", 4, 7, "EC"),
    ("BEC714x", "Professional Elective Course", 3, 7, "EC"),
    ("BEC755x", "Open Elective Course", 3, 7, "EC"),
    ("BEC786", "Major Project Phase-II", 6, 7, "EC"),
    ("BEC801x", "Professional Elective (Online Courses)", 3, 8, "EC"),
    ("BEC802x", "Open Elective (Online Courses)", 3, 8, "EC"),
    ("BEC803", "Internship (Industry/Research)", 10, 8, "EC"),
    ("BMATE101", "Mathematics-I for EEE Streams", 4, 1, "EE"),
    ("BPHYE102", "Applied Physics for EEE Stream", 4, 1, "EE"),
    ("BEEE103", "Elements of Electrical Engineering", 3, 1, "EE"),
    ("BESCK104x", "Engineering Science Course-I", 3, 1, "EE"),
    ("BETCK105x", "Emerging Technology Course-I / Programming Language Course-I", 3, 1, "EE"),
    ("BENGK106", "Communicative English / Professional Writing Skills in English", 1, 1, "EE"),
    ("BKSKK107", "Samskrutika Kannada / Balake Kannada / Indian Constitution", 1, 1, "EE"),
    ("BIDTK158", "Innovation and Design Thinking / Scientific Foundations of Health", 1, 1, "EE"),
    ("BMATE201", "Mathematics-II for EEE Streams", 4, 2, "EE"),
    ("BCHEE202", "Chemistry for EES", 4, 2, "EE"),
    ("BCEDK203", "Computer-Aided Engineering Drawing", 3, 2, "EE"),
    ("BESCK204x", "Engineering Science Course-II", 3, 2, "EE"),
    ("BPLCK205x", "Programming Language Course-II / Emerging Technology Course-II", 3, 2, "EE"),
    ("BPWKS206", "Professional Writing Skills in English / Communicative English", 1, 2, "EE"),
    ("BICOK207", "Indian Constitution / Samskrutika Kannada / Balake Kannada", 1, 2, "EE"),
    ("BSFHK258", "Scientific Foundations of Health / Innovation and Design Thinking", 1, 2, "EE"),
    ("BEE301", "Engineering Mathematics for EEE", 3, 3, "EE"),
    ("BEE302", "Electric Circuit Analysis", 4, 3, "EE"),
    ("BEE303", "Analog Electronic Circuits", 4, 3, "EE"),
    ("BEE304", "Transformers and Generators", 3, 3, "EE"),
    ("BEEL305", "Transformers and Generators Lab", 1, 3, "EE"),
    ("BEE306x", "Engineering Science Course (ESC/ETC/PLC)-III", 3, 3, "EE"),
    ("BSCK307", "Social Connect and Responsibility", 1, 3, "EE"),
    ("BEE358x", "Ability Enhancement Course/Skill Enhancement Course-III", 1, 3, "EE"),
    ("BEE401", "Electric Motors", 3, 4, "EE"),
    ("BEE402", "Transmission and Distribution", 4, 4, "EE"),
    ("BEE403", "Microcontrollers", 4, 4, "EE"),
    ("BEEL404", "Electric Motors Lab", 1, 4, "EE"),
    ("BEE405x", "Engineering Science Course (ESC/ETC/PLC)-IV", 3, 4, "EE"),
    ("BEE456x", "Ability Enhancement Course/Skill Enhancement Course-IV", 1, 4, "EE"),
    ("BBOK407", "Biology For Engineers", 3, 4, "EE"),
    ("BUHK408", "Universal Human Values Course", 1, 4, "EE"),
    ("BEE501", "Engineering Management and Entrepreneurship", 3, 5, "EE"),
    ("BEE502", "Signals & DSP", 4, 5, "EE"),
    ("BEE503", "Power Electronics", 4, 5, "EE"),
    ("BEEL504", "Power Electronics Lab", 1, 5, "EE"),
    ("BEE515x", "Professional Elective Course-I", 3, 5, "EE"),
    ("BEE586", "Mini Project", 2, 5, "EE"),
    ("BRMK557", "Research Methodology and IPR", 3, 5, "EE"),
    ("BESK508", "Environmental Studies", 2, 5, "EE"),
    ("BEE601", "Power System Analysis-I", 4, 6, "EE"),
    ("BEE602", "Control Systems", 4, 6, "EE"),
    ("BEE613x", "Professional Elective Course-II", 3, 6, "EE"),
    ("BEE654x", "Open Elective Course-I", 3, 6, "EE"),
    ("BEE685", "Project Phase I", 2, 6, "EE"),
    ("BEEL606", "Control System Lab", 1, 6, "EE"),
    ("BEE657x", "Ability Enhancement Course/Skill Development Course-V", 1, 6, "EE"),
    ("BEE701", "Switchgear and Protection", 4, 7, "EE"),
    ("BEE702", "Industrial Drives and Applications", 4, 7, "EE"),
    ("BEE703", "Power System Analysis-II", 4, 7, "EE"),
    ("BEE714x", "Professional Elective Course-III", 3, 7, "EE"),
    ("BEE755x", "Open Elective Course-II", 3, 7, "EE"),
    ("BEE786", "Major Project Phase-II", 6, 7, "EE"),
    ("BEE801x", "Professional Elective (Online Courses)", 3, 8, "EE"),
    ("BEE802x", "Open Elective (Online Courses)", 3, 8, "EE"),
    ("BEE803", "Internship (Industry/Research)", 10, 8, "EE"),
    ("BMATC101", "Mathematics-I for Civil Engineering Stream", 4, 1, "CV"),
    ("BPHYC102", "Applied Physics for Civil Engineering Stream", 4, 1, "CV"),
    ("BCIVC103", "Engineering Mechanics", 3, 1, "CV"),
    ("BESCK104X", "Engineering Science Course-I", 3, 1, "CV"),
    ("BETCK105X", "Emerging Technology Course-I / Programming Language Course-I", 3, 1, "CV"),
    ("BENGK106", "Communicative English / Professional Writing Skills in English", 1, 1, "CV"),
    ("BKSKK107", "Samskrutika Kannada / Balake Kannada / Indian Constitution", 1, 1, "CV"),
    ("BIDTK158", "Innovation and Design Thinking / Scientific Foundations of Health", 1, 1, "CV"),
    ("BMATC201", "Mathematics-II for Civil Engineering Stream", 4, 2, "CV"),
    ("BCHEC202", "Applied Chemistry for Civil Engineering Stream", 4, 2, "CV"),
    ("BCEDK203", "Computer-Aided Engineering Drawing", 3, 2, "CV"),
    ("BESCK204X", "Engineering Science Course-II", 3, 2, "CV"),
    ("BPLCK205X", "Programming Language Course-II / Emerging Technology Course-II", 3, 2, "CV"),
    ("BPWSK206", "Professional Writing Skills in English / Communicative English", 1, 2, "CV"),
    ("BICOK207", "Indian Constitution / Samskrutika Kannada / Balake Kannada", 1, 2, "CV"),
    ("BSFHK258", "Scientific Foundations of Health / Innovation and Design Thinking", 1, 2, "CV"),
    ("BCV301", "Strength of Materials", 3, 3, "CV"),
    ("BCV302", "Engineering Survey", 4, 3, "CV"),
    ("BCV303", "Engineering Geology", 4, 3, "CV"),
    ("BCV304", "Water Supply and Waste Water Engineering", 3, 3, "CV"),
    ("BCV305", "Computer Aided Building Planning and Drawing", 1, 3, "CV"),
    ("BCV306X", "Engineering Science Course (ESC/ETC/PLC)", 3, 3, "CV"),
    ("BSCK307", "Social Connect and Responsibility", 1, 3, "CV"),
    ("BCV358X", "Ability Enhancement Course/Skill Enhancement Course-III", 1, 3, "CV"),
    ("BCV401", "Analysis of Structures", 3, 4, "CV"),
    ("BCV402", "Fluid Mechanics and Hydraulics", 4, 4, "CV"),
    ("BCV403", "Transportation Engineering", 4, 4, "CV"),
    ("BCVL404", "Building Materials Testing Lab", 1, 4, "CV"),
    ("BCV405X", "Engineering Science Course (ESC/ETC/PLC)", 3, 4, "CV"),
    ("BCV456X", "Ability Enhancement Course/Skill Enhancement Course-IV", 1, 4, "CV"),
    ("BBOK407", "Biology For Engineers", 3, 4, "CV"),
    ("BUHK408", "Universal Human Values Course", 1, 4, "CV"),
    ("BCV501", "Construction Management and Entrepreneurship", 3, 5, "CV"),
    ("BCV502", "Geotechnical Engineering", 4, 5, "CV"),
    ("BCV503", "Concrete Technology", 4, 5, "CV"),
    ("BCV504", "Environmental Engineering Lab", 1, 5, "CV"),
    ("BCV515X", "Professional Elective Course", 3, 5, "CV"),
    ("BCV586", "Mini Project/Extensive Survey Project", 2, 5, "CV"),
    ("BRMK557", "Research Methodology and IPR", 3, 5, "CV"),
    ("BESK508", "Environmental Studies", 2, 5, "CV"),
    ("BCV601", "Design of RCC Structures", 4, 6, "CV"),
    ("BCV602", "Irrigation Engineering and Hydraulic Structures", 4, 6, "CV"),
    ("BCV613X", "Professional Elective Course", 3, 6, "CV"),
    ("BCV654X", "Open Elective Course", 3, 6, "CV"),
    ("BCV685", "Major Project Phase I", 2, 6, "CV"),
    ("BCVL606", "Software Application Lab", 1, 6, "CV"),
    ("BCV657X", "Ability Enhancement Course/Skill Development Course-V", 1, 6, "CV"),
    ("BCV701", "Design of Steel Structures", 4, 7, "CV"),
    ("BCV702", "Estimation and Contract Management", 4, 7, "CV"),
    ("BCV703", "Prestressed Concrete", 4, 7, "CV"),
    ("BCV714X", "Professional Elective Course", 3, 7, "CV"),
    ("BCV755X", "Open Elective Course", 3, 7, "CV"),
    ("BCV786", "Major Project Phase-II", 6, 7, "CV"),
    ("BCV801X", "Professional Elective Course (Online)", 3, 8, "CV"),
    ("BCV802X", "Open Elective Course (Online)", 3, 8, "CV"),
    ("BCV803", "Internship (Industry/Research)", 10, 8, "CV"),
    ("BMATM101", "Mathematics-I for Mechanical Engineering Stream", 4, 1, "ME"),
    ("BPHYM102", "Applied Physics for ME Stream", 4, 1, "ME"),
    ("BEMEM103", "Elements of Mechanical Engineering", 3, 1, "ME"),
    ("BESCK104x", "Engineering Science Course-I", 3, 1, "ME"),
    ("BETCK105x", "Emerging Technology Course-I / Programming Language Course-I", 3, 1, "ME"),
    ("BENGK106", "Communicative English / Professional Writing Skills in English", 1, 1, "ME"),
    ("BKSKK107", "Samskrutika Kannada / Balake Kannada / Indian Constitution", 1, 1, "ME"),
    ("BIDTK158", "Innovation and Design Thinking / Scientific Foundations of Health", 1, 1, "ME"),
    ("BMATM201", "Mathematics-II for Mechanical Engineering Stream", 4, 2, "ME"),
    ("BCHEM202", "Applied Chemistry for ME Stream", 4, 2, "ME"),
    ("BCEDK203", "Computer-Aided Engineering Drawing", 3, 2, "ME"),
    ("BESCK204x", "Engineering Science Course-II", 3, 2, "ME"),
    ("BPLCK205x", "Programming Language Course-II / Emerging Technology Course-II", 3, 2, "ME"),
    ("BPWSK206", "Professional Writing Skills in English / Communicative English", 1, 2, "ME"),
    ("BICOK207", "Indian Constitution / Samskrutika Kannada / Balake Kannada", 1, 2, "ME"),
    ("BSFHK258", "Scientific Foundations for Health / Innovation and Design Thinking", 1, 2, "ME"),
    ("BME301", "Mechanics of Materials", 3, 3, "ME"),
    ("BME302", "Manufacturing Process", 4, 3, "ME"),
    ("BME303", "Material Science and Engineering", 4, 3, "ME"),
    ("BME304", "Basic Thermodynamics", 3, 3, "ME"),
    ("BMEL305", "Introduction to Modelling and Design for Manufacturing", 1, 3, "ME"),
    ("BME306x", "Engineering Science/Emerging Technology/Programming Language Course", 3, 3, "ME"),
    ("BSCK307", "Social Connect and Responsibility", 1, 3, "ME"),
    ("BME358x", "Ability Enhancement Course/Skill Enhancement Course-III", 1, 3, "ME"),
    ("BME401", "Applied Thermodynamics", 3, 4, "ME"),
    ("BME402", "Machining Science & Metrology", 4, 4, "ME"),
    ("BME403", "Fluid Mechanics", 4, 4, "ME"),
    ("BME404", "Mechanical Measurements and Metrology Lab", 1, 4, "ME"),
    ("BME405x", "Engineering Science/Emerging Technology/Programming Language Course", 3, 4, "ME"),
    ("BME456x", "Ability Enhancement Course/Skill Enhancement Course-IV", 1, 4, "ME"),
    ("BBOK407", "Biology For Engineers", 3, 4, "ME"),
    ("BUHK408", "Universal Human Values Course", 1, 4, "ME"),
    ("BME501", "Industrial Management & Entrepreneurship", 3, 5, "ME"),
    ("BME502", "Turbo Machines", 4, 5, "ME"),
    ("BME503", "Theory of Machines", 4, 5, "ME"),
    ("BME504L", "CNC Programming and 3-D Printing Lab", 1, 5, "ME"),
    ("BME515x", "Professional Elective-I", 3, 5, "ME"),
    ("BME586", "Mini Project", 2, 5, "ME"),
    ("BRMK557", "Research Methodology and IPR", 3, 5, "ME"),
    ("BESK508", "Environmental Studies", 2, 5, "ME"),
    ("BME601", "Heat Transfer", 4, 6, "ME"),
    ("BME602", "Machine Design", 4, 6, "ME"),
    ("BME613x", "Professional Elective-II", 3, 6, "ME"),
    ("BME654x", "Open Elective-I", 3, 6, "ME"),
    ("BME685", "Major Project Phase-I", 2, 6, "ME"),
    ("BMEL606L", "Design Lab", 1, 6, "ME"),
    ("BME657x", "Ability Enhancement Course/Skill Development Course-V", 1, 6, "ME"),
    ("BME701", "Finite Element Methods", 4, 7, "ME"),
    ("BME702", "Hydraulics and Pneumatics", 4, 7, "ME"),
    ("BME703", "Control Engineering", 4, 7, "ME"),
    ("BME714x", "Professional Elective-III", 3, 7, "ME"),
    ("BME755x", "Open Elective-II", 3, 7, "ME"),
    ("BME786", "Major Project Phase-II", 6, 7, "ME"),
    ("BME801x", "Professional Elective-IV (Online Courses)", 3, 8, "ME"),
    ("BME802x", "Open Elective-III (Online Courses)", 3, 8, "ME"),
    ("BME803", "Internship (Industry/Research)", 10, 8, "ME"),
]

CATALOG_2025 = [
    ("1BMATS101", "Calculus and Linear Algebra (CSE Stream)", 4, 1, "CS"),
    ("1BPHYS102", "Quantum Physics and Applications (CSE Stream)", 4, 1, "CS"),
    ("1BCEDS103", "Computer-Aided Engineering Drawing (CSE Stream)", 3, 1, "CS"),
    ("1BXXX104x", "Engineering Science Course-I (Elective)", 3, 1, "CS"),
    ("1BEIT105", "Programming in C", 3, 1, "CS"),
    ("1BPOPL107", "C Programming Laboratory", 1, 1, "CS"),
    ("1BIDTL158", "Innovation and Design Thinking Lab", 1, 1, "CS"),
    ("1BKSK109", "Samskrutika Kannada / Balake Kannada", 1, 1, "CS"),
    ("1BMATS201", "Numerical Methods (CSE Stream)", 4, 2, "CS"),
    ("1BCHES202", "Applied Chemistry for Smart Systems (CSE)", 4, 2, "CS"),
    ("1BAIA203", "Introduction to AI and Applications", 3, 2, "CS"),
    ("1BESC204x", "Engineering Science Course-II (Elective)", 3, 2, "CS"),
    ("1BPLC205B", "Python Programming (CSE and Allied Programmes)", 4, 2, "CS"),
    ("1BENG206", "Communication Skills", 1, 2, "CS"),
    ("1BPRJ258", "Interdisciplinary Project-Based Learning", 1, 2, "CS"),
    ("1BMATCS301", "Probability, Distributions and Statistics", 4, 3, "CS"),
    ("1BCS302", "Object Oriented Programming with Java", 4, 3, "CS"),
    ("1BCS303", "Digital Design and Computer Organization", 4, 3, "CS"),
    ("1BCS304", "Operating Systems", 3, 3, "CS"),
    ("1BCS305", "Data Structures and Applications", 3, 3, "CS"),
    ("1BCSL306", "Data Structures Laboratory", 1, 3, "CS"),
    ("1BCSL307A", "Project Management (with Git)", 1, 3, "CS"),
    ("1BCP308", "Community Project (Project-Based Learning) / Societal Project", 1, 3, "CS"),
    ("1BCS401", "Discrete Mathematics and Graph Theory", 4, 4, "CS"),
    ("1BCS402", "Database Management Systems", 4, 4, "CS"),
    ("1BCS403", "Computer Networks", 4, 4, "CS"),
    ("1BCS404", "Design and Analysis of Algorithms", 4, 4, "CS"),
    ("1BCSL405", "Algorithms Laboratory", 1, 4, "CS"),
    ("1BXXL406x", "Ability Enhancement Course Laboratory (React / UI-UX)", 1, 4, "CS"),
    ("1BCS407", "Biology for Computer Engineers", 2, 4, "CS"),
    ("1BEP408", "Environmental Science Project", 1, 4, "CS"),
    ("1BCS501", "Software Engineering and Project Management", 3, 5, "CS"),
    ("1BCS502", "Machine Learning", 4, 5, "CS"),
    ("1BCS503", "Theory of Computation", 4, 5, "CS"),
    ("1BCS504", "Computer Vision", 3, 5, "CS"),
    ("1BXX505x", "Professional Elective Course-I (Soft Computing/Distributed Computing/NLP/Unix)", 3, 5, "CS"),
    ("1BRM506", "Research Methodology and IPR", 2, 5, "CS"),
    ("1BCSL507", "Web Technology Laboratory", 1, 5, "CS"),
    ("1BCS508", "Hackathon-Based Project", 2, 5, "CS"),
    ("1BCS601", "Advanced Java Programming", 4, 6, "CS"),
    ("1BCS602", "Cryptography and Network Security", 3, 6, "CS"),
    ("1BCS603", "High Performance Computing", 3, 6, "CS"),
    ("1BCS604", "Internet of Things", 3, 6, "CS"),
    ("1BXX605x", "Professional Elective Course-II (AI/RPA UiPath/Compiler Design/Modern Arch)", 3, 6, "CS"),
    ("1BCSL606", "IoT Laboratory", 1, 6, "CS"),
    ("1BXXL607x", "Ability Enhancement Course Laboratory (Full Stack/DevOps/GenAI)", 1, 6, "CS"),
    ("1BCS608", "Capstone Project - Phase I", 3, 6, "CS"),
    ("1BCS701", "Big Data Analytics", 4, 7, "CS"),
    ("1BXX702x", "Professional Elective Course-III (Deep Learning/Edge AI/Ethical Hacking/OR)", 3, 7, "CS"),
    ("1BXX703x", "Professional Elective Course-IV (Agentic AI/Prompt Eng/Quantum/Cloud)", 3, 7, "CS"),
    ("1BXX704x", "Open Elective Course-I (Data Structures/Algorithms/DB Systems/Foreign Lang)", 3, 7, "CS"),
    ("1BCS705", "Capstone Project - Phase-II", 7, 7, "CS"),
    ("1Bxx801x", "Professional Elective-V (NPTEL/VTU Online Course)", 3, 8, "CS"),
    ("1Bxx802x", "Open Elective-II (NPTEL/VTU Online Course)", 3, 8, "CS"),
    ("1Bxx803x", "Internship (15 weeks / 90 working days)", 9, 8, "CS"),
    ("1BMATS101", "Calculus and Linear Algebra (CSE Stream)", 4, 1, "AI"),
    ("1BPHYS102", "Quantum Physics and Applications (CSE Stream)", 4, 1, "AI"),
    ("1BCEDS103", "Computer-Aided Engineering Drawing (CSE Stream)", 3, 1, "AI"),
    ("1BXXX104x", "Engineering Science Course-I (Elective)", 3, 1, "AI"),
    ("1BEIT105", "Programming in C", 3, 1, "AI"),
    ("1BPOPL107", "C Programming Laboratory", 1, 1, "AI"),
    ("1BIDTL158", "Innovation and Design Thinking Lab", 1, 1, "AI"),
    ("1BKSK109", "Samskrutika Kannada / Balake Kannada", 1, 1, "AI"),
    ("1BMATS201", "Numerical Methods (CSE Stream)", 4, 2, "AI"),
    ("1BCHES202", "Applied Chemistry for Smart Systems (CSE)", 4, 2, "AI"),
    ("1BAIA203", "Introduction to AI and Applications", 3, 2, "AI"),
    ("1BESC204x", "Engineering Science Course-II (Elective)", 3, 2, "AI"),
    ("1BPLC205B", "Python Programming (CSE and Allied Programmes)", 4, 2, "AI"),
    ("1BENG206", "Communication Skills", 1, 2, "AI"),
    ("1BPRJ258", "Interdisciplinary Project-Based Learning", 1, 2, "AI"),
    ("1BMATCS301", "Probability, Distributions and Statistics", 4, 3, "AI"),
    ("1BCS302", "Object Oriented Programming with Java", 4, 3, "AI"),
    ("1BCS303", "Digital Design and Computer Organization", 4, 3, "AI"),
    ("1BCS304", "Operating Systems", 3, 3, "AI"),
    ("1BCS305", "Data Structures and Applications", 3, 3, "AI"),
    ("1BCSL306", "Data Structures Laboratory", 1, 3, "AI"),
    ("1BXXL307x", "Ability Enhancement Course (Laboratory)", 1, 3, "AI"),
    ("1BCP308", "Community Project (Project-Based Learning) / Societal Project", 1, 3, "AI"),
    ("1BAI401", "Discrete Mathematics and Optimization Techniques", 4, 4, "AI"),
    ("1BAI402", "Design and Analysis of Algorithms", 4, 4, "AI"),
    ("1BAI403", "Database Management Systems", 4, 4, "AI"),
    ("1BAI404", "Machine Learning", 4, 4, "AI"),
    ("1BAIL405", "Machine Learning Laboratory", 1, 4, "AI"),
    ("1BXXL406x", "Ability Enhancement Course", 1, 4, "AI"),
    ("1BCS407", "Biology for Computer Engineers", 2, 4, "AI"),
    ("1BEP408", "Environmental Science Project", 1, 4, "AI"),
    ("1BCS501", "Software Engineering and Project Management", 3, 5, "AI"),
    ("1BAI502", "Artificial Intelligence", 4, 5, "AI"),
    ("1BCS503", "Theory of Computation", 4, 5, "AI"),
    ("1BAI504", "Computer Networks", 3, 5, "AI"),
    ("1BXX505x", "Professional Elective Course-I", 3, 5, "AI"),
    ("1BRM506", "Research Methodology and IPR", 2, 5, "AI"),
    ("1BAIL507", "Data Visualization Laboratory", 1, 5, "AI"),
    ("1BAI508", "Hackathon-Based Project", 2, 5, "AI"),
    ("1BCS601", "Advanced Java Programming", 4, 6, "AI"),
    ("1BIS602", "Information and Network Security", 3, 6, "AI"),
    ("1BAI603", "Deep Learning", 3, 6, "AI"),
    ("1BAI604", "Natural Language Processing", 3, 6, "AI"),
    ("1BXX605x", "Professional Elective Course-II", 3, 6, "AI"),
    ("1BAIL606", "Deep Learning Laboratory", 1, 6, "AI"),
    ("1BXXL607x", "Ability Enhancement Course Laboratory", 1, 6, "AI"),
    ("1BAI608", "Capstone Project - Phase I", 3, 6, "AI"),
    ("1BAD701", "High Performance Computing in Artificial Intelligence", 4, 7, "AI"),
    ("1BXX702x", "Professional Elective Course-III", 3, 7, "AI"),
    ("1BXX703x", "Professional Elective Course-IV", 3, 7, "AI"),
    ("1BXX704x", "Open Elective Course-I", 3, 7, "AI"),
    ("1BAI705", "Capstone Project - Phase-II", 7, 7, "AI"),
    ("1Bxx801x", "Professional Elective-V (NPTEL/VTU Online Course)", 3, 8, "AI"),
    ("1Bxx802x", "Open Elective-II (NPTEL/VTU Online Course)", 3, 8, "AI"),
    ("1Bxx803x", "Internship (15 weeks / 90 working days)", 9, 8, "AI"),
    ("1BMATS101", "Calculus and Linear Algebra (CSE Stream)", 4, 1, "DS"),
    ("1BPHYS102", "Quantum Physics and Applications (CSE Stream)", 4, 1, "DS"),
    ("1BCEDS103", "Computer-Aided Engineering Drawing (CSE Stream)", 3, 1, "DS"),
    ("1BXXX104x", "Engineering Science Course-I (Elective)", 3, 1, "DS"),
    ("1BEIT105", "Programming in C", 3, 1, "DS"),
    ("1BPOPL107", "C Programming Laboratory", 1, 1, "DS"),
    ("1BIDTL158", "Innovation and Design Thinking Lab", 1, 1, "DS"),
    ("1BKSK109", "Samskrutika Kannada / Balake Kannada", 1, 1, "DS"),
    ("1BMATS201", "Numerical Methods (CSE Stream)", 4, 2, "DS"),
    ("1BCHES202", "Applied Chemistry for Smart Systems (CSE)", 4, 2, "DS"),
    ("1BAIA203", "Introduction to AI and Applications", 3, 2, "DS"),
    ("1BESC204x", "Engineering Science Course-II (Elective)", 3, 2, "DS"),
    ("1BPLC205B", "Python Programming (CSE and Allied Programmes)", 4, 2, "DS"),
    ("1BENG206", "Communication Skills", 1, 2, "DS"),
    ("1BPRJ258", "Interdisciplinary Project-Based Learning", 1, 2, "DS"),
    ("1BMATCS301", "Probability, Distributions and Statistics", 4, 3, "DS"),
    ("1BCS302", "Object Oriented Programming with Java", 4, 3, "DS"),
    ("1BCS303", "Digital Design and Computer Organization", 4, 3, "DS"),
    ("1BCS304", "Operating Systems", 3, 3, "DS"),
    ("1BCS305", "Data Structures and Applications", 3, 3, "DS"),
    ("1BCSL306", "Data Structures Laboratory", 1, 3, "DS"),
    ("1BXXL307x", "Ability Enhancement Course (Exploratory Data Analysis / Git)", 1, 3, "DS"),
    ("1BCP308", "Community Project (Project-Based Learning) / Societal Project", 1, 3, "DS"),
    ("1BAI401", "Discrete Mathematics and Optimization Techniques", 4, 4, "DS"),
    ("1BAI402", "Design and Analysis of Algorithms", 4, 4, "DS"),
    ("1BAI403", "Database Management Systems", 4, 4, "DS"),
    ("1BAI404", "Machine Learning", 4, 4, "DS"),
    ("1BAIL405", "Machine Learning Laboratory", 1, 4, "DS"),
    ("1BXXL406x", "Ability Enhancement Course (Mobile Dev/UI-UX/R Programming/NoSQL)", 1, 4, "DS"),
    ("1BCS407", "Biology for Computer Engineers", 2, 4, "DS"),
    ("1BEP408", "Environmental Science Project", 1, 4, "DS"),
    ("1BCS501", "Software Engineering and Project Management", 3, 5, "DS"),
    ("1BDS502", "No SQL Databases", 4, 5, "DS"),
    ("1BCS503", "Theory of Computation", 4, 5, "DS"),
    ("1BAI504", "Computer Networks", 3, 5, "DS"),
    ("1BXX505x", "Professional Elective Course-I (Image/Video Proc, AI, NLP, Multimodal)", 3, 5, "DS"),
    ("1BRM506", "Research Methodology and IPR (Online)", 2, 5, "DS"),
    ("1BAIL507", "Data Visualization Laboratory", 1, 5, "DS"),
    ("1BDS508", "Hackathon-Based Project", 2, 5, "DS"),
    ("1BCS601", "Advanced Java Programming", 4, 6, "DS"),
    ("1BAD602", "Data Security & Privacy", 3, 6, "DS"),
    ("1BAI603", "Deep Learning", 3, 6, "DS"),
    ("1BAD604", "Big Data Analytics", 3, 6, "DS"),
    ("1BXX605x", "Professional Elective Course-II (Prompt Eng/RPA/IoT/Time Series)", 3, 6, "DS"),
    ("1BDSL606", "Big Data Analytics Laboratory", 1, 6, "DS"),
    ("1BXXL607x", "Ability Enhancement Course Laboratory (GenAI/OOP-UML/DevOps/React)", 1, 6, "DS"),
    ("1BDS608", "Capstone Project - Phase I", 3, 6, "DS"),
    ("1BAD701", "High Performance Computing in Artificial Intelligence", 4, 7, "DS"),
    ("1BXX702x", "Professional Elective Course-III (Data Engg & MLOps/Business Analytics)", 3, 7, "DS"),
    ("1BXX703x", "Professional Elective Course-IV (Explainable Learning/Quantum/Blockchain/SNA)", 3, 7, "DS"),
    ("1BXX704x", "Open Elective Course-I (Stats in DS/BI & Analytics/EDA w Python/Foreign Lang)", 3, 7, "DS"),
    ("1BDS705", "Capstone Project - Phase-II", 7, 7, "DS"),
    ("1BIKS706", "Indian Knowledge System (VTU online Course)", 0, 7, "DS"),
    ("1Bxx801x", "Professional Elective-V (NPTEL/VTU Online Course)", 3, 8, "DS"),
    ("1Bxx802x", "Open Elective-II (NPTEL/VTU Online Course)", 3, 8, "DS"),
    ("1Bxx803x", "Internship (15 weeks or 90 working days)", 9, 8, "DS"),
    ("1BMATE101", "Differential Calculus and Linear Algebra (EEE Stream)", 4, 1, "EC"),
    ("1BPHEC102", "Quantum Physics and Electronic Sensors (ECE Stream)", 4, 1, "EC"),
    ("1BCEDEC103", "Computer-Aided Engineering Drawing for ECE Stream", 3, 1, "EC"),
    ("1BESC104x", "Engineering Science Course-I (Elective)", 3, 1, "EC"),
    ("1BECE105", "Fundamentals of Electronics & Communication Engineering", 3, 1, "EC"),
    ("1BECEL107", "Fundamentals of Electronics & Communication Engineering Lab", 1, 1, "EC"),
    ("1BIDTL158", "Innovation and Design Thinking Lab", 1, 1, "EC"),
    ("1BKSK109", "Samskrutika Kannada / Balake Kannada", 1, 1, "EC"),
    ("1BMATE201", "Calculus, Laplace Transform and Numerical Techniques (EEE Stream)", 4, 2, "EC"),
    ("1BCHEE202", "Applied Chemistry for Emerging Electronics and Futuristic Devices (EEE, ECE)", 4, 2, "EC"),
    ("1BAIA203", "Introduction to AI and Applications", 3, 2, "EC"),
    ("1BESC204x", "Engineering Science Course-II (Elective)", 3, 2, "EC"),
    ("1BPLC205x", "Programming Language Course (Elective)", 4, 2, "EC"),
    ("1BENG206", "Communication Skills", 1, 2, "EC"),
    ("1BPRJ258", "Interdisciplinary Project-Based Learning", 1, 2, "EC"),
    ("1BMATEC301", "Transform Techniques and Optimization Theory", 4, 3, "EC"),
    ("1BEC302", "Digital System Design Using Verilog", 4, 3, "EC"),
    ("1BEC303", "Network Analysis", 4, 3, "EC"),
    ("1BEC304", "Analog Electronics and Linear Integrated Circuits", 3, 3, "EC"),
    ("1BEC305", "Python Programming", 3, 3, "EC"),
    ("1BECL306", "Analog Electronics and Linear Integrated Circuits Lab", 1, 3, "EC"),
    ("1BECL307x", "Ability Enhancement Course Laboratory (Elective)", 1, 3, "EC"),
    ("1BCP308", "Community Project (Project-Based Learning) / Societal Project", 1, 3, "EC"),
    ("1BMATEC401", "Mathematics for Machine Learning", 3, 4, "EC"),
    ("1BEC402", "Applied Computer Organization and Microcontrollers", 4, 4, "EC"),
    ("1BEC403", "Control Systems", 4, 4, "EC"),
    ("1BEC404", "Signals and Systems", 3, 4, "EC"),
    ("1BECL405", "Signals and Analog Communications Lab", 1, 4, "EC"),
    ("1BECL406x", "Ability Enhancement Course Laboratory (Elective)", 1, 4, "EC"),
    ("1BEC407", "Biology for Electrical and Electronics Engineers", 2, 4, "EC"),
    ("1BEP408", "Environmental Science Project", 1, 4, "EC"),
    ("1BEC409", "Introduction to Analog Communication Systems", 3, 4, "EC"),
    ("1BEC501", "Economics and Management (HSMC)", 3, 5, "EC"),
    ("1BEC502", "Digital Signal Processing", 4, 5, "EC"),
    ("1BEC503", "Engineering Electromagnetics", 3, 5, "EC"),
    ("1BEC504", "Introduction to VLSI Design", 3, 5, "EC"),
    ("1BEC505x", "Professional Elective Course-I", 3, 5, "EC"),
    ("1BRM506", "Research Methodology and IPR", 2, 5, "EC"),
    ("1BECL507", "VLSI Lab", 1, 5, "EC"),
    ("1BEC508", "Hackathon-Based Project", 2, 5, "EC"),
    ("1BEC601", "Computer Networking and Communication", 4, 6, "EC"),
    ("1BEC602", "Antenna and Wireless Communication", 3, 6, "EC"),
    ("1BEC603", "Digital Communication Systems", 3, 6, "EC"),
    ("1BEC604", "FPGA Based System Design", 3, 6, "EC"),
    ("1BEC605x", "Professional Elective Course-II", 3, 6, "EC"),
    ("1BECL606", "Communication Lab", 1, 6, "EC"),
    ("1BECL607x", "Ability Enhancement Course Laboratory (Elective)", 1, 6, "EC"),
    ("1BEC608", "Capstone Project - Phase I", 3, 6, "EC"),
    ("1BEC701", "Edge Computing with Tiny ML", 4, 7, "EC"),
    ("1BEC702x", "Professional Elective Course-III", 3, 7, "EC"),
    ("1BEC703x", "Professional Elective Course-IV", 3, 7, "EC"),
    ("1BEC704x", "Open Elective Course-I", 3, 7, "EC"),
    ("1BEC705", "Capstone Project - Phase II", 7, 7, "EC"),
    ("1BEC801x", "Professional Elective-V (NPTEL/VTU Online Course)", 3, 8, "EC"),
    ("1BEC802x", "Open Elective-II (NPTEL/VTU Online Course)", 3, 8, "EC"),
    ("1BEC803x", "Internship (15 weeks / 90 working days)", 9, 8, "EC"),
    ("1BMATE101", "Differential Calculus and Linear Algebra (EEE Stream)", 4, 1, "EE"),
    ("1BPHEE102", "Physics for EEE Stream [pattern-inferred, not independently verified]", 4, 1, "EE"),
    ("1BEEE105", "Fundamentals of Electrical & Electronics Engineering [pattern-inferred]", 3, 1, "EE"),
    ("1BESC104x", "Engineering Science Course-I (Elective)", 3, 1, "EE"),
    ("1BIDTL158", "Innovation and Design Thinking Lab", 1, 1, "EE"),
    ("1BKSK109", "Samskrutika Kannada / Balake Kannada", 1, 1, "EE"),
    ("1BMATE201", "Calculus, Laplace Transform and Numerical Techniques (EEE Stream)", 4, 2, "EE"),
    ("1BCHEE202", "Applied Chemistry for Emerging Electronics and Futuristic Devices (EEE, ECE)", 4, 2, "EE"),
    ("1BAIA203", "Introduction to AI and Applications", 3, 2, "EE"),
    ("1BESC204x", "Engineering Science Course-II (Elective)", 3, 2, "EE"),
    ("1BPLC205x", "Programming Language Course (Elective)", 4, 2, "EE"),
    ("1BENG206", "Communication Skills", 1, 2, "EE"),
    ("1BPRJ258", "Interdisciplinary Project-Based Learning", 1, 2, "EE"),
    ("1BMAT301", "Mathematics-III for EEE", 4, 3, "EE"),
    ("1BEE302", "Analog Electronic Circuits", 4, 3, "EE"),
    ("1BEE303", "Electric Circuit Analysis", 4, 3, "EE"),
    ("1BEE304", "Digital Electronic Circuits", 3, 3, "EE"),
    ("1BEE305", "Transformers and Generators", 3, 3, "EE"),
    ("1BEEL306", "Transformers and Generators Lab", 1, 3, "EE"),
    ("1BEEL307x", "Ability Enhancement Course Laboratory", 1, 3, "EE"),
    ("1BCP308", "Community Project (Project-Based Learning) / Societal Project", 1, 3, "EE"),
    ("1BEE401", "Electric Motors", 3, 4, "EE"),
    ("1BEE402", "Microcontroller", 4, 4, "EE"),
    ("1BEE403", "Field Theory", 4, 4, "EE"),
    ("1BEE404", "Transmission and Distribution", 3, 4, "EE"),
    ("1BEEL405", "Electric Motors Lab", 1, 4, "EE"),
    ("1BEEL406", "Ability Enhancement Course Laboratory", 1, 4, "EE"),
    ("1BEE407", "Biology for Electrical Engineers", 2, 4, "EE"),
    ("1BEP408", "Environmental Science Project", 1, 4, "EE"),
    ("1BEE409", "Electric Power Generation and Economics", 3, 4, "EE"),
    ("1BMATC101", "Differential Calculus and Linear Algebra (Civil Stream)", 4, 1, "CV"),
    ("1BPHYC102", "Physics for Civil Engineering Stream [pattern-inferred, not independently verified]", 4, 1, "CV"),
    ("1BCVE105", "Fundamentals of Civil Engineering [pattern-inferred]", 3, 1, "CV"),
    ("1BESC104x", "Engineering Science Course-I (Elective)", 3, 1, "CV"),
    ("1BIDTL158", "Innovation and Design Thinking Lab", 1, 1, "CV"),
    ("1BKSK109", "Samskrutika Kannada / Balake Kannada", 1, 1, "CV"),
    ("1BMATC201", "Mathematics-II for Civil Engineering Stream [pattern-inferred]", 4, 2, "CV"),
    ("1BCHEC202", "Applied Chemistry for Civil Engineering Stream [pattern-inferred]", 4, 2, "CV"),
    ("1BAIA203", "Introduction to AI and Applications", 3, 2, "CV"),
    ("1BESC204x", "Engineering Science Course-II (Elective)", 3, 2, "CV"),
    ("1BPLC205x", "Programming Language Course (Elective)", 4, 2, "CV"),
    ("1BENG206", "Communication Skills", 1, 2, "CV"),
    ("1BPRJ258", "Interdisciplinary Project-Based Learning", 1, 2, "CV"),
    ("1MATCV301", "Probability and Statistics", 4, 3, "CV"),
    ("1BCV302", "Fluid Mechanics and Hydraulic Machinery", 4, 3, "CV"),
    ("1BCV303", "Solid Mechanics", 4, 3, "CV"),
    ("1BCV304", "Building Materials and Construction Methods", 3, 3, "CV"),
    ("1BCV305", "Engineering Geology for Infrastructure Projects", 3, 3, "CV"),
    ("1BCVL306", "Auto CAD and 3D Modelling of Buildings", 1, 3, "CV"),
    ("1BCVL307x", "Ability Enhancement Course Laboratory", 1, 3, "CV"),
    ("1BCP308", "Community Project (Project-Based Learning) / Societal Project", 1, 3, "CV"),
    ("1BCV401", "Surveying and Geospatial Techniques for Infrastructure Projects", 3, 4, "CV"),
    ("1BCV402", "Water Supply and Sanitary Engineering", 4, 4, "CV"),
    ("1BCV403", "Analysis of Structures", 4, 4, "CV"),
    ("1BCV404", "Building Information Modelling (BIM)", 3, 4, "CV"),
    ("1BCVL405", "Surveying and Geospatial Engineering Laboratory", 1, 4, "CV"),
    ("1BCVL406X", "Ability Enhancement Course Laboratory", 1, 4, "CV"),
    ("1BCV407", "Biology for Civil and Infrastructure Engineers", 2, 4, "CV"),
    ("1BEP408", "Environmental Science Project", 1, 4, "CV"),
    ("1BCV409", "Concrete Technology", 3, 4, "CV"),
    ("1BMATM101", "Differential Calculus and Linear Algebra (ME Stream)", 4, 1, "ME"),
    ("1BPHYM102", "Physics of Materials (Mech Stream)", 4, 1, "ME"),
    ("1BCEDM103", "Computer-Aided Engineering Drawing for ME Stream", 3, 1, "ME"),
    ("1BXXX104x", "Engineering Science Course-I (Elective)", 3, 1, "ME"),
    ("1Bxxx105x", "Programme Specific Course (Elective)", 3, 1, "ME"),
    ("1BxxxL107x", "Programme-Specific Course Lab (Elective)", 1, 1, "ME"),
    ("1BIDTL158", "Innovation and Design Thinking Lab", 1, 1, "ME"),
    ("1BKSK109", "Samskrutika Kannada / Balake Kannada", 1, 1, "ME"),
    ("1BMATM201", "Multivariable Calculus and Numerical Methods (ME Stream)", 4, 2, "ME"),
    ("1BCHEM202", "Applied Chemistry for Advanced Metal Protection and Sustainable Energy Systems (ME)", 4, 2, "ME"),
    ("1BAIA203", "Introduction to AI and Applications", 3, 2, "ME"),
    ("1BESC204x", "Engineering Science Course-II (Elective)", 3, 2, "ME"),
    ("1BPLC205x", "Programming Language Course (Elective)", 4, 2, "ME"),
    ("1BENG206", "Communication Skills", 1, 2, "ME"),
    ("1BPRJ258", "Interdisciplinary Project-Based Learning", 1, 2, "ME"),
    ("1BMATM301", "Transforms and Statistics", 4, 3, "ME"),
    ("1BME302", "Materials Science and Metallurgy", 4, 3, "ME"),
    ("1BME303", "Basic Thermodynamics", 3, 3, "ME"),
    ("1BME304", "Mechanics of Materials", 3, 3, "ME"),
    ("1BME305", "Manufacturing Technology - I", 3, 3, "ME"),
    ("1BMEL306", "Computer Aided Machine Drawing Lab", 2, 3, "ME"),
    ("1BMEL307x", "Ability Enhancement Course Laboratory", 1, 3, "ME"),
    ("1BCP308", "Community Project (Project-Based Learning) / Societal Project", 1, 3, "ME"),
    ("1BMATM401", "Complex Analysis and Probability Distributions", 3, 4, "ME"),
    ("1BME402", "Manufacturing Technology - II", 4, 4, "ME"),
    ("1BME403", "Applied Thermodynamics", 4, 4, "ME"),
    ("1BME404", "Fluid Mechanics", 3, 4, "ME"),
    ("1BMEL405", "Mechanical Measurements and Metrology Lab", 1, 4, "ME"),
    ("1BMEL406x", "Ability Enhancement Course Laboratory", 1, 4, "ME"),
    ("1BME407", "Biology for Engineers", 2, 4, "ME"),
    ("1BEP408", "Environmental Science Project", 1, 4, "ME"),
    ("1BME409", "Kinematics of Machines", 3, 4, "ME"),
    ("1BMATM101", "Differential Calculus and Linear Algebra (ME Stream)", 4, 1, "RI"),
    ("1BPHYM102", "Physics of Materials (Mech Stream)", 4, 1, "RI"),
    ("1BCEDM103", "Computer-Aided Engineering Drawing for ME Stream", 3, 1, "RI"),
    ("1BXXX104x", "Engineering Science Course-I (Elective)", 3, 1, "RI"),
    ("1Bxxx105x", "Programme Specific Course (Elective)", 3, 1, "RI"),
    ("1BxxxL107x", "Programme-Specific Course Lab (Elective)", 1, 1, "RI"),
    ("1BIDTL158", "Innovation and Design Thinking Lab", 1, 1, "RI"),
    ("1BKSK109", "Samskrutika Kannada / Balake Kannada", 1, 1, "RI"),
    ("1BMATM201", "Multivariable Calculus and Numerical Methods (ME Stream)", 4, 2, "RI"),
    ("1BCHEM202", "Applied Chemistry for Advanced Metal Protection and Sustainable Energy Systems (ME)", 4, 2, "RI"),
    ("1BAIA203", "Introduction to AI and Applications", 3, 2, "RI"),
    ("1BESC204x", "Engineering Science Course-II (Elective)", 3, 2, "RI"),
    ("1BPLC205x", "Programming Language Course (Elective)", 4, 2, "RI"),
    ("1BENG206", "Communication Skills", 1, 2, "RI"),
    ("1BPRJ258", "Interdisciplinary Project-Based Learning", 1, 2, "RI"),
    ("1BRI301", "Discrete Mathematics and Probability Theory", 4, 3, "RI"),
    ("1BRI302", "Data Structures and Algorithms", 4, 3, "RI"),
    ("1BRI303", "Mechanics of Materials", 4, 3, "RI"),
    ("1BRI304", "Analog and Digital Electronic Circuits (ADEC)", 3, 3, "RI"),
    ("1BRI305", "Fundamentals of Industrial Robots", 3, 3, "RI"),
    ("1BRIL306", "Computer Aided Modelling Lab", 1, 3, "RI"),
    ("1BRIL307", "Analog and Digital Electronic Circuits Lab", 1, 3, "RI"),
    ("1BCP308", "Community Project (Project-Based Learning) / Societal Project", 1, 3, "RI"),
    ("1BRI401", "Robot Kinematics and Dynamics", 3, 4, "RI"),
    ("1BRI402", "Object-Oriented Programming", 4, 4, "RI"),
    ("1BRI403", "Control Systems", 4, 4, "RI"),
    ("1BRI404", "Sensors and Actuators", 3, 4, "RI"),
    ("1BRIL405", "Sensors and Actuators Laboratory", 1, 4, "RI"),
    ("1BRIL406", "Industrial Robot Laboratory", 1, 4, "RI"),
    ("1BRI407", "Programme Specific Biology", 2, 4, "RI"),
    ("1BEP408", "Environmental Science Project", 1, 4, "RI"),
    ("1BRI409", "Design of Robotic Components", 3, 4, "RI"),
]


def print_catalog():
    print("\n" + "="*80)
    print("   VTU COMPLETE SYLLABUS CATALOG (2022 & 2025)")
    print("="*80)

    branches_2022 = sorted(set(r[4] for r in CATALOG_2022))
    print(f"  [2022 Scheme] Validated Branches: {', '.join(branches_2022)}")

    print("-" * 80)
    for b in branches_2022:
        total = sum(r[2] for r in CATALOG_2022 if r[4] == b)
        sems = sorted(set(r[3] for r in CATALOG_2022 if r[4] == b))
        print(f"  Branch: {b:<4} | Semesters: {sems} | Total Credits: {total}")

    branches_2025 = sorted(set(r[4] for r in CATALOG_2025))
    print("\n" + "="*80)
    print("   [2025 Scheme] Branch Mapping (curriculum still rolling out sem-by-sem)")
    print("="*80)
    print(f"  Validated Branches: {', '.join(branches_2025)}")
    print("-" * 80)
    for b in branches_2025:
        total = sum(r[2] for r in CATALOG_2025 if r[4] == b)
        sems = sorted(set(r[3] for r in CATALOG_2025 if r[4] == b))
        print(f"  Branch: {b:<4} | Semesters: {sems} | Total Credits: {total}")

if __name__ == "__main__":
    print_catalog()
